//! Render a [`Litmus`] as a `herd7` C11 litmus test, so the language-level
//! axiomatic models shipped with herdtools7 (`rc11.cat`, `c11_*.cat`) can
//! enumerate the outcome set the Rust/C++20 memory model permits.
//!
//! Translation notes (these are *model inputs*, recorded in the evidence bundle):
//! * `AtomicU32` ↦ `atomic_int` (herd's C frontend models integers abstractly;
//!   width does not matter for the relations checked).
//! * Rust `compare_exchange(exp, new, succ, fail)` ↦
//!   `atomic_compare_exchange_strong_explicit(loc, e, new, succ, fail)` where `e` is a
//!   thread-private non-atomic cell pre-initialised to `exp` (herd's C frontend requires
//!   the "expected" argument to be a memory location, not `&reg`). The register receives
//!   `*e` after the call: C semantics write the observed value into `*expected` on failure
//!   and leave it equal to `exp` on success, which is exactly Rust's "previous value" in
//!   both branches.
//! * `fence(o)` ↦ `atomic_thread_fence(o)`.
//! * `locations [..]` lists every register so herd7 prints full final states; the final
//!   condition is `exists (true)` so *every* state is enumerated. The outcome set, not
//!   a single predicate, is the object of comparison.

use crate::litmus::{Instr, Litmus, RmwKind};
use std::fmt::Write;

pub fn render(litmus: &Litmus) -> String {
    let mut s = String::new();
    let _ = writeln!(s, "C {}", sanitize(&litmus.name));
    let _ = writeln!(
        s,
        "(* generated by rustlitmus; digest {} *)",
        litmus.digest()
    );
    // Header: shared atomics plus one private "expected" cell per CAS.
    let mut header: Vec<String> = litmus
        .locations
        .iter()
        .map(|l| format!("[{l}] = 0"))
        .collect();
    let mut cas_cells: Vec<Vec<String>> = vec![Vec::new(); litmus.threads.len()];
    for (t, th) in litmus.threads.iter().enumerate() {
        for (i, ins) in th.instrs.iter().enumerate() {
            if let Instr::Rmw {
                kind: RmwKind::CompareExchange { expected, .. },
                ..
            } = ins
            {
                let cell = format!("e{t}_{i}");
                header.push(format!("[{cell}] = {expected}"));
                cas_cells[t].push(cell);
            }
        }
    }
    let _ = writeln!(s, "{{ {}; }}", header.join("; "));
    let _ = writeln!(s);
    let mut all_regs = Vec::new();
    for (t, th) in litmus.threads.iter().enumerate() {
        let mut params: Vec<String> = litmus
            .locations
            .iter()
            .map(|l| format!("atomic_int *{l}"))
            .collect();
        for c in &cas_cells[t] {
            params.push(format!("int *{c}"));
        }
        let _ = writeln!(s, "P{t}({}) {{", params.join(", "));
        let mut cas_idx = 0;
        for ins in &th.instrs {
            match ins {
                Instr::Store { loc, value, ord } => {
                    let _ = writeln!(
                        s,
                        "  atomic_store_explicit({}, {value}, {});",
                        litmus.locations[*loc],
                        ord.c11()
                    );
                }
                Instr::Load { loc, reg, ord } => {
                    let _ = writeln!(
                        s,
                        "  int r{reg} = atomic_load_explicit({}, {});",
                        litmus.locations[*loc],
                        ord.c11()
                    );
                    all_regs.push(format!("{t}:r{reg}"));
                }
                Instr::Rmw {
                    loc,
                    reg,
                    value,
                    ord,
                    kind,
                } => {
                    all_regs.push(format!("{t}:r{reg}"));
                    match kind {
                        RmwKind::Swap => {
                            let _ = writeln!(
                                s,
                                "  int r{reg} = atomic_exchange_explicit({}, {value}, {});",
                                litmus.locations[*loc],
                                ord.c11()
                            );
                        }
                        RmwKind::FetchAdd => {
                            let _ = writeln!(
                                s,
                                "  int r{reg} = atomic_fetch_add_explicit({}, {value}, {});",
                                litmus.locations[*loc],
                                ord.c11()
                            );
                        }
                        RmwKind::CompareExchange { failure, .. } => {
                            let cell = &cas_cells[t][cas_idx];
                            cas_idx += 1;
                            let _ = writeln!(
                                s,
                                "  atomic_compare_exchange_strong_explicit({}, {cell}, {value}, {}, {});",
                                litmus.locations[*loc],
                                ord.c11(),
                                failure.c11()
                            );
                            let _ = writeln!(s, "  int r{reg} = *{cell};");
                        }
                    }
                }
                Instr::Fence { ord } => {
                    let _ = writeln!(s, "  atomic_thread_fence({});", ord.c11());
                }
            }
        }
        let _ = writeln!(s, "}}");
        let _ = writeln!(s);
    }
    if !all_regs.is_empty() {
        let _ = writeln!(s, "locations [{};]", all_regs.join("; "));
    }
    let _ = writeln!(s, "exists (true)");
    s
}

pub fn sanitize(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '-' || c == '_' || c == '+' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::litmus::{Ord, Thread};

    #[test]
    fn renders_c11_cas() {
        let l = Litmus {
            name: "cas".into(),
            locations: vec!["x".into()],
            threads: vec![Thread {
                instrs: vec![Instr::Rmw {
                    loc: 0,
                    reg: 0,
                    value: 1,
                    ord: Ord::Release,
                    kind: RmwKind::CompareExchange {
                        expected: 0,
                        failure: Ord::Acquire,
                    },
                }],
            }],
        };
        let s = render(&l);
        assert!(s.contains("{ [x] = 0; [e0_0] = 0; }"));
        assert!(s.contains("P0(atomic_int *x, int *e0_0) {"));
        assert!(s.contains("atomic_compare_exchange_strong_explicit(x, e0_0, 1, memory_order_release, memory_order_acquire);"));
        assert!(s.contains("int r0 = *e0_0;"));
        assert!(s.contains("locations [0:r0;]"));
        assert!(s.trim_end().ends_with("exists (true)"));
    }
}
