//! Render a [`Litmus`] as a standalone Rust program.
//!
//! Layout (this is load-bearing for the rest of the pipeline):
//!
//! * Each thread body is emitted as `#[inline(never)] #[no_mangle] pub extern "C" fn
//!   rl_thread_N(locs: &Locs, regs: &mut [u32; R])`. The thread function is the unit
//!   whose MIR / LLVM IR / assembly are captured and whose assembly is lifted into the
//!   architecture-level litmus test. Because it is `extern "C"` and `#[no_mangle]`, it has
//!   a stable symbol and a stable ABI across compilers and optimisation levels.
//! * The harness runs `ITER` rounds. Each round resets all locations to zero, starts all
//!   threads at a barrier, runs one execution of the litmus body per thread, joins, and
//!   records the register tuple. Outcome histogram is printed as JSON on stdout.
//! * The harness uses `std::thread::scope` so it is also directly interpretable by Miri
//!   (which understands `std::thread`).
//!
//! The harness never reads a location non-atomically while a thread may be running, so
//! the program is free of data races by construction.

use crate::litmus::{Instr, Litmus, RmwKind};
use std::fmt::Write;

pub struct RenderedRust {
    pub source: String,
    /// Symbol names of the thread functions, in thread order.
    pub thread_symbols: Vec<String>,
}

pub fn thread_symbol(t: usize) -> String {
    format!("rl_thread_{t}")
}

fn instr(out: &mut String, ins: &Instr, litmus: &Litmus) {
    let loc = |l: usize| format!("locs.{}", litmus.locations[l]);
    match ins {
        Instr::Store { loc: l, value, ord } => {
            let _ = writeln!(out, "    {}.store({value}, {});", loc(*l), ord.rust());
        }
        Instr::Load { loc: l, reg, ord } => {
            let _ = writeln!(out, "    regs[{reg}] = {}.load({});", loc(*l), ord.rust());
        }
        Instr::Rmw {
            loc: l,
            reg,
            value,
            ord,
            kind,
        } => match kind {
            RmwKind::Swap => {
                let _ = writeln!(
                    out,
                    "    regs[{reg}] = {}.swap({value}, {});",
                    loc(*l),
                    ord.rust()
                );
            }
            RmwKind::FetchAdd => {
                let _ = writeln!(
                    out,
                    "    regs[{reg}] = {}.fetch_add({value}, {});",
                    loc(*l),
                    ord.rust()
                );
            }
            RmwKind::CompareExchange { expected, failure } => {
                let _ = writeln!(
                    out,
                    "    regs[{reg}] = match {}.compare_exchange({expected}, {value}, {}, {}) {{ Ok(v) => v, Err(v) => v }};",
                    loc(*l),
                    ord.rust(),
                    failure.rust()
                );
            }
        },
        Instr::Fence { ord } => {
            let _ = writeln!(out, "    fence({});", ord.rust());
        }
    }
}

pub fn render(litmus: &Litmus) -> RenderedRust {
    let mut s = String::new();
    let _ = writeln!(
        s,
        "// Generated by rustlitmus from litmus {:?} (digest {}).",
        litmus.name,
        litmus.digest()
    );
    let _ = writeln!(
        s,
        "// Do not edit: every layer of the evidence chain is derived from the abstract litmus."
    );
    let _ = writeln!(
        s,
        "#![allow(unused_imports, dead_code, non_snake_case, unused_assignments)]"
    );
    let _ = writeln!(
        s,
        "use std::sync::atomic::{{AtomicU32, AtomicUsize, Ordering::*, fence}};"
    );
    let _ = writeln!(s, "use std::collections::BTreeMap;");
    let _ = writeln!(s);
    let _ = writeln!(s, "#[repr(C)]");
    let _ = writeln!(s, "pub struct Locs {{");
    for l in &litmus.locations {
        // Each location on its own cache line so the hardware test probes ordering,
        // not false sharing.
        let _ = writeln!(s, "    pub {l}: AtomicU32, pub _pad_{l}: [u8; 60],");
    }
    let _ = writeln!(s, "}}");
    let _ = writeln!(s);
    let _ = writeln!(s, "impl Locs {{");
    let _ = writeln!(s, "    const fn new() -> Self {{");
    let _ = writeln!(s, "        Locs {{");
    for l in &litmus.locations {
        let _ = writeln!(s, "            {l}: AtomicU32::new(0), _pad_{l}: [0; 60],");
    }
    let _ = writeln!(s, "        }}");
    let _ = writeln!(s, "    }}");
    let _ = writeln!(s, "    fn reset(&self) {{");
    for l in &litmus.locations {
        let _ = writeln!(s, "        self.{l}.store(0, Relaxed);");
    }
    let _ = writeln!(s, "    }}");
    let _ = writeln!(s, "}}");
    let _ = writeln!(s);

    let mut thread_symbols = Vec::new();
    for (t, th) in litmus.threads.iter().enumerate() {
        let sym = thread_symbol(t);
        let nregs = th.num_regs();
        let _ = writeln!(s, "#[inline(never)]");
        let _ = writeln!(s, "#[no_mangle]");
        let _ = writeln!(
            s,
            "pub extern \"C\" fn {sym}(locs: &Locs, regs: &mut [u32; {nregs}]) {{"
        );
        for ins in &th.instrs {
            instr(&mut s, ins, litmus);
        }
        let _ = writeln!(s, "}}");
        let _ = writeln!(s);
        thread_symbols.push(sym);
    }

    let nthreads = litmus.threads.len();
    let _ = writeln!(s, "const NTHREADS: usize = {nthreads};");
    let _ = writeln!(s);
    let _ = writeln!(
        s,
        "/// Spin barrier: all threads arrive, then all leave together."
    );
    let _ = writeln!(
        s,
        "struct Barrier {{ count: AtomicUsize, gen: AtomicUsize }}"
    );
    let _ = writeln!(s, "impl Barrier {{");
    let _ = writeln!(s, "    const fn new() -> Self {{ Barrier {{ count: AtomicUsize::new(0), gen: AtomicUsize::new(0) }} }}");
    let _ = writeln!(s, "    fn wait(&self) {{");
    let _ = writeln!(s, "        let g = self.gen.load(Acquire);");
    let _ = writeln!(
        s,
        "        if self.count.fetch_add(1, AcqRel) + 1 == NTHREADS {{"
    );
    let _ = writeln!(s, "            self.count.store(0, Relaxed);");
    let _ = writeln!(s, "            self.gen.store(g + 1, Release);");
    let _ = writeln!(s, "        }} else {{");
    let _ = writeln!(
        s,
        "            // Spin briefly, then yield: with more threads than CPUs a pure spin"
    );
    let _ = writeln!(
        s,
        "            // barrier starves the thread that must arrive last."
    );
    let _ = writeln!(s, "            let mut spins = 0u32;");
    let _ = writeln!(s, "            while self.gen.load(Acquire) == g {{");
    let _ = writeln!(s, "                spins += 1;");
    let _ = writeln!(s, "                if spins < 2000 {{ std::hint::spin_loop(); }} else {{ std::thread::yield_now(); }}");
    let _ = writeln!(s, "            }}");
    let _ = writeln!(s, "        }}");
    let _ = writeln!(s, "    }}");
    let _ = writeln!(s, "}}");
    let _ = writeln!(s);
    let _ = writeln!(s, "fn main() {{");
    let _ = writeln!(
        s,
        "    let iters: usize = std::env::args().nth(1).and_then(|a| a.parse().ok()).unwrap_or(1);"
    );
    let _ = writeln!(s, "    let locs = Locs::new();");
    let _ = writeln!(s, "    let barrier = Barrier::new();");
    let _ = writeln!(
        s,
        "    let mut hist: BTreeMap<Vec<Vec<u32>>, u64> = BTreeMap::new();"
    );
    let _ = writeln!(
        s,
        "    // One scope per round keeps the program interpretable by Miri and exhaustive model"
    );
    let _ = writeln!(
        s,
        "    // checkers (each round is a bounded, join-terminated execution)."
    );
    let _ = writeln!(s, "    for _ in 0..iters {{");
    let _ = writeln!(s, "        locs.reset();");
    let _ = writeln!(
        s,
        "        let outcome: Vec<Vec<u32>> = std::thread::scope(|sc| {{"
    );
    let _ = writeln!(s, "            let mut hs = Vec::new();");
    for (t, th) in litmus.threads.iter().enumerate() {
        let nregs = th.num_regs();
        let sym = thread_symbol(t);
        let _ = writeln!(s, "            hs.push(sc.spawn(|| {{ let mut regs = [0u32; {nregs}]; barrier.wait(); {sym}(&locs, &mut regs); regs.to_vec() }}));");
    }
    let _ = writeln!(
        s,
        "            hs.into_iter().map(|h| h.join().unwrap()).collect()"
    );
    let _ = writeln!(s, "        }});");
    let _ = writeln!(s, "        *hist.entry(outcome).or_insert(0) += 1;");
    let _ = writeln!(s, "    }}");
    let _ = writeln!(
        s,
        "    // Machine-readable histogram: one line per outcome, `count<TAB>t0r0,t0r1|t1r0`."
    );
    let _ = writeln!(s, "    for (o, n) in &hist {{");
    let _ = writeln!(s, "        let cells: Vec<String> = o.iter().map(|regs| regs.iter().map(|v| v.to_string()).collect::<Vec<_>>().join(\",\")).collect();");
    let _ = writeln!(
        s,
        "        println!(\"{{}}\\t{{}}\", n, cells.join(\"|\"));"
    );
    let _ = writeln!(s, "    }}");
    let _ = writeln!(s, "}}");

    RenderedRust {
        source: s,
        thread_symbols,
    }
}

/// Minimal single-execution variant for exhaustive model checking (Miri-GenMC).
///
/// GenMC's exploration is exponential in the number of shared-memory events, so this
/// rendering strips everything the hardware harness needs and GenMC does not: no spin
/// barrier, no histogram, no per-round reset, one `thread::scope` with one execution.
/// Thread bodies are the *same functions* (`rl_thread_N`) so the program under test is
/// unchanged; only the driver differs. Output is one histogram line with count 1.
pub fn render_single(litmus: &Litmus) -> String {
    let full = render(litmus).source;
    // Keep everything up to and including the thread functions (i.e. drop from
    // `const NTHREADS` onwards) and append a minimal main.
    let cut = full.find("const NTHREADS").expect("renderer layout");
    let mut s = full[..cut].to_string();
    let _ = writeln!(s, "fn main() {{");
    let _ = writeln!(s, "    let locs = Locs::new();");
    let _ = writeln!(
        s,
        "    let outcome: Vec<Vec<u32>> = std::thread::scope(|sc| {{"
    );
    let _ = writeln!(s, "        let mut hs = Vec::new();");
    for (t, th) in litmus.threads.iter().enumerate() {
        let nregs = th.num_regs();
        let sym = thread_symbol(t);
        let _ = writeln!(s, "        hs.push(sc.spawn(|| {{ let mut regs = [0u32; {nregs}]; {sym}(&locs, &mut regs); regs.to_vec() }}));");
    }
    let _ = writeln!(
        s,
        "        hs.into_iter().map(|h| h.join().unwrap()).collect()"
    );
    let _ = writeln!(s, "    }});");
    let _ = writeln!(s, "    let cells: Vec<String> = outcome.iter().map(|regs| regs.iter().map(|v| v.to_string()).collect::<Vec<_>>().join(\",\")).collect();");
    let _ = writeln!(s, "    println!(\"1\\t{{}}\", cells.join(\"|\"));");
    let _ = writeln!(s, "}}");
    s
}

/// Parse the histogram printed by a rendered program.
pub fn parse_histogram(
    stdout: &str,
) -> Result<std::collections::BTreeMap<crate::litmus::Outcome, u64>, String> {
    let mut m = std::collections::BTreeMap::new();
    for line in stdout.lines() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let (n, cells) = line
            .split_once('\t')
            .ok_or_else(|| format!("malformed histogram line: {line:?}"))?;
        let n: u64 = n
            .parse()
            .map_err(|e| format!("bad count in {line:?}: {e}"))?;
        let mut regs = Vec::new();
        for cell in cells.split('|') {
            if cell.is_empty() {
                regs.push(Vec::new());
                continue;
            }
            let vals: Result<Vec<u32>, _> = cell.split(',').map(|v| v.parse::<u32>()).collect();
            regs.push(vals.map_err(|e| format!("bad register value in {line:?}: {e}"))?);
        }
        *m.entry(crate::litmus::Outcome(regs)).or_insert(0) += n;
    }
    Ok(m)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::litmus::{Litmus, Ord, Thread};

    fn sb() -> Litmus {
        Litmus {
            name: "SB".into(),
            locations: vec!["x".into(), "y".into()],
            threads: vec![
                Thread {
                    instrs: vec![
                        Instr::Store {
                            loc: 0,
                            value: 1,
                            ord: Ord::Relaxed,
                        },
                        Instr::Load {
                            loc: 1,
                            reg: 0,
                            ord: Ord::Relaxed,
                        },
                    ],
                },
                Thread {
                    instrs: vec![
                        Instr::Store {
                            loc: 1,
                            value: 1,
                            ord: Ord::Relaxed,
                        },
                        Instr::Load {
                            loc: 0,
                            reg: 0,
                            ord: Ord::Relaxed,
                        },
                    ],
                },
            ],
        }
    }

    #[test]
    fn renders_thread_functions() {
        let r = render(&sb());
        assert!(r
            .source
            .contains("pub extern \"C\" fn rl_thread_0(locs: &Locs, regs: &mut [u32; 1])"));
        assert!(r.source.contains("locs.x.store(1, Relaxed);"));
        assert!(r.source.contains("regs[0] = locs.y.load(Relaxed);"));
        assert_eq!(r.thread_symbols, vec!["rl_thread_0", "rl_thread_1"]);
    }

    #[test]
    fn parses_histogram() {
        let h = parse_histogram("3\t0|1\n1\t1|1\n").unwrap();
        assert_eq!(h.len(), 2);
        assert_eq!(h[&crate::litmus::Outcome(vec![vec![0], vec![1]])], 3);
        assert!(parse_histogram("garbage").is_err());
        assert!(parse_histogram("x\t0|1").is_err());
    }

    #[test]
    fn rendering_is_deterministic() {
        assert_eq!(render(&sb()).source, render(&sb()).source);
    }
}
